### PR TITLE
Multiple build runners

### LINKED ISSUE #1396: zls is broken in bun's repo
### Zig Version

0.11.0-dev.4006+bf827d0b5

### Zig Language Server Version

HEAD (latest published to VSCode)

### Steps to Reproduce

1. `gh clone oven-sh/bun`
2. Open a .zig file which uses the `bun` identifier (almost all of them)
3. No completions appear.

Looks like zls is failing to load build.zig in bun's repository. This started happening yesterday or today. I don't think we made any relevant changes.

Any identifiers which reference an import no longer have completions
image

Note that `bun` here is `const bun = @import("root").bun`. The `@import("root")` seems to not resolve, most likely due to failing to load build.zig.

Relevant log (note the invalid unicode character):
```js
error: (store ): Failed to execute build runner to collect build configuration, command:
info : (server): Setting configuration...
```

Complete log:
```js
info : ( main ): Starting ZLS 0.12.0-dev.2+9532f4a @ '/Users/jarred/Library/Application Support/Code/User/globalStorage/ziglang.vscode-zig/zls_install/zls'
info : (config): Using zig executable '/Users/jarred/zig/master/files/zig'
info : (config): Using zig lib path '/Users/jarred/zig/0.11.0-dev.4006+bf827d0b5/files/lib'
info : (config): Using build runner global cache path '/Users/jarred/.cache/zig'
info : (config): Detected runtime zig version: '0.11.0-dev.4006+bf827d0b5'
info : (server): client is 'Visual Studio Code-1.81.0'
info : (server): zls initializing
info : (server): Server.ClientCapabilities{ .supports_snippets = true, .supports_apply_edits = true, .supports_will_save = true, .supports_will_save_wait_until = true, .supports_publish_diagnostics = true, .supports_code_action_fixall = true, .hover_supports_md = true, .completion_doc_supports_md = true, .label_details_support = true, .supports_configuration = true, .supports_workspace_did_change_configuration_dynamic_registration = true, .supports_textDocument_definition_linkSupport = true }
info : (server): Using offset encoding: utf-16
warning: (server): Zig `0.11.0-dev.4006+bf827d0b5` is older than ZLS `0.12.0-dev.2+9532f4a`. Update Zig to avoid unexpected behavior.
info : (server): Setting configuration...
warning: (server): Ignoring new value for "zls.record_session_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.replay_session_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.builtin_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.build_runner_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.global_cache_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.build_runner_global_cache_path": the given new value is invalid
info : (config): Using zig executable '/Users/jarred/zig/master/files/zig'
info : (config): Using zig lib path '/Users/jarred/zig/0.11.0-dev.4006+bf827d0b5/files/lib'
info : (config): Using build runner global cache path '/Users/jarred/.cache/zig'
info : (config): Detected runtime zig version: '0.11.0-dev.4006+bf827d0b5'
error: (store ): Failed to execute build runner to collect build configuration, command:
info : (server): Setting configuration...
warning: (server): Ignoring new value for "zls.record_session_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.replay_session_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.builtin_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.build_runner_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.global_cache_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.build_runner_global_cache_path": the given new value is invalid
info : (config): Using zig executable '/Users/jarred/zig/master/files/zig'
info : (config): Using zig lib path '/Users/jarred/zig/0.11.0-dev.4006+bf827d0b5/files/lib'
info : (config): Using build runner global cache path '/Users/jarred/.cache/zig'
info : (config): Detected runtime zig version: '0.11.0-dev.4006+bf827d0b5'
info : (server): Setting configuration...
warning: (server): Ignoring new value for "zls.record_session_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.replay_session_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.builtin_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.build_runner_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.global_cache_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.build_runner_global_cache_path": the given new value is invalid
info : (config): Using zig executable '/Users/jarred/zig/master/files/zig'
info : (config): Using zig lib path '/Users/jarred/zig/0.11.0-dev.4006+bf827d0b5/files/lib'
info : (config): Using build runner global cache path '/Users/jarred/.cache/zig'
info : (config): Detected runtime zig version: '0.11.0-dev.4006+bf827d0b5'
info : (server): Setting configuration...
warning: (server): Ignoring new value for "zls.record_session_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.replay_session_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.builtin_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.build_runner_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.global_cache_path": the given new value is invalid
warning: (server): Ignoring new value for "zls.build_runner_global_cache_path": the given new value is invalid
info : (config): Using zig executable '/Users/jarred/zig/master/files/zig'
info : (config): Using zig lib path '/Users/jarred/zig/0.11.0-dev.4006+bf827d0b5/files/lib'
info : (config): Using build runner global cache path '/Users/jarred/.cache/zig'
info : (config): Detected runtime zig version: '0.11.0-dev.4006+bf827d0b5'
warning: (store ): Document already open: file:///Users/jarred/Code/bun/src/bun.js/javascript.zig
```

### Expected Behavior

Completions should appear for imports.

### Actual Behavior

Completions do not appear for imports.

### PR DESCRIPTION
**Pull request by leecannon**
This PR uses a different build runner based on the runtime zig version.

This is not exactly aligned with the decision in https://github.com/zigtools/zls/issues/1020 but the maintenance burden to do this is not large:

- On a new major release being tagged make a copy of `build_runner/master.zig` for that release and update the `build_runner/BuildRunnerVersion.zig` enum.
- If the data output by the build runner is changed (`build_runner/BuildConfig.zig`) then the older build runners will need to be updated to match the json format.

Fixes #1396

### CODE REVIEW

File: src/Server.zig [hunk 1]
```diff
@@ -1050,15 +1050,31 @@ fn resolveConfiguration(server: *Server, config_arena: std.mem.Allocator, config
...
+
+        try build_runner_file.writeAll(
+            switch (build_runner_version) {
+                inline else => |tag| @embedFile("build_runner/" ++ @tagName(tag) ++ ".zig"),
+            },
+        );
 
-        const file = try std.fs.createFileAbsolute(config.build_runner_path.?, .{});
-        defer file.close();
+        log.debug("using build runner version: {s}", .{@tagName(build_runner_version)});
```
Comment (Techatrix) [inline src/Server.zig:1075]: I think its better to move this log message somewhere [here](https://github.com/zigtools/zls/blob/9c1f5c8163d64128f032d302dce881ae381d8aa8/src/Server.zig#L867-L889) for consistency.

**Review by Techatrix — CHANGES_REQUESTED** [review]
If you want, you can apply this patch to simplify the logic in `BuildRunnerVersion.zig`
I guess you did this because you didn't want to have the patch version in the enum but adding it in makes it so much simpler.

```patch
diff --git a/src/build_runner/0.10.zig b/src/build_runner/0.10.0.zig
similarity index 100%
rename from src/build_runner/0.10.zig
rename to src/build_runner/0.10.0.zig
diff --git a/src/build_runner/0.11.zig b/src/build_runner/0.11.0.zig
similarity index 100%
rename from src/build_runner/0.11.zig
rename to src/build_runner/0.11.0.zig
diff --git a/src/build_runner/BuildRunnerVersion.zig b/src/build_runner/BuildRunnerVersion.zig
index 7a2028a..24ef916 100644
--- a/src/build_runner/BuildRunnerVersion.zig
+++ b/src/build_runner/BuildRunnerVersion.zig
@@ -5,8 +5,8 @@ const build_options = @import("build_options");
 // There should be no need to have a build runner for minor patches (e.g. 0.10.1)
 pub const BuildRunnerVersion = enum {
     master,
-    @"0.11",
-    @"0.10",
+    @"0.11.0",
+    @"0.10.0",
 
     pub fn selectBuildRunnerVersion(runtime_zig_version: std.SemanticVersion) BuildRunnerVersion {
         const runtime_zig_version_simple = std.SemanticVersion{
@@ -23,44 +23,18 @@ pub const BuildRunnerVersion = enum {
         return switch (runtime_zig_version_simple.order(zls_version_simple)) {
             .eq, .gt => .master,
             .lt => blk: {
-                const build_runners = BuildRunnerVersion.non_master_build_runners;
-
-                for (build_runners) |build_runner| {
-                    switch (runtime_zig_version.order(build_runner.version)) {
-                        .eq, .gt => break :blk build_runner.tag,
+                const available_versions = std.meta.tags(BuildRunnerVersion);
+                for (available_versions[1..]) |build_runner_version| {
+                    const version = std.SemanticVersion.parse(@tagName(build_runner_version)) catch unreachable;
+                    switch (runtime_zig_version.order(version)) {
+                        .eq, .gt => break :blk build_runner_version,
                         .lt => {},
                     }
                 }
 
                 // failed to find compatible build runner, falling back to oldest supported version
-                break :blk BuildRunnerVersion.oldest_version;
+                break :blk available_versions[available_versions.len - 1];
             },
         };
     }
-
-    const oldest_version = blk: {
-        const tags = std.meta.tags(BuildRunnerVersion);
-        break :blk tags[tags.len - 1];
-    };
-
-    const NonMasterBuildRunner = struct { tag: BuildRunnerVersion, version: std.SemanticVersion };
-
-    const non_master_build_runners = blk: {
-        const tags = std.meta.tags(BuildRunnerVersion);
-
-        var build_runners: [tags.len - 1]NonMasterBuildRunner = .{};
-
-        var i: usize = 0;
-
-        for (tags) |tag| {
-            if (tag == .master) continue;
-            build_runners[i] = .{
-                .tag = tag,
-                .version = std.SemanticVersion.parse(@tagName(tag) ++ ".0") catch unreachable,
-            };
-            i += 1;
-        }
-
-        break :blk build_runners;
-    };
 };
```

**Review by Techatrix — APPROVED** [review]
