### PR TITLE
Some `.enum_literal` completions fixes

### LINKED ISSUE #1618: type functions that accept struct arguments give completions for the argument struct instead of the returned struct
### Zig Version

0.12.0-dev.1680+be6f76655

### Zig Language Server Version

0.12.0-dev.248+62f17ab

### Steps to Reproduce

```zig
const std = @import("std");

pub fn main() void {
   _ = std.heap.GeneralPurposeAllocator(.{}){<cursor>};
}
```
request completions

### Expected Behavior

list of completions should be of the fields from the GPA type

### Actual Behavior

fields from the config param are given instead

### PR DESCRIPTION
**Pull request by nullptrdevs**
Fixes #1618 and https://github.com/zigtools/zls/issues/1617#issuecomment-1823583412

### CODE REVIEW

File: src/features/completions.zig [hunk 1]
```diff
@@ -1366,13 +1335,27 @@ fn collectFieldAccessContainerNodes(
...
+                const body = node_type.handle.tree.nodes.items(.data)[node_type.type.data.other].rhs;
+                node_type = try analyser.resolveReturnType(full_fn_proto, node_type.handle, if (has_body) body else null) orelse return;
+                // `E!T`
+                if (node_type.type.data == .other and node_type.handle.tree.nodes.items(.tag)[node_type.type.data.other] == .error_union) {
+                    const node_data = node_type.handle.tree.nodes.items(.data)[node_type.type.data.other];
+                    if (node_data.rhs == 0) return;
+                    node_type = try analyser.resolveTypeOfNode(.{ .node = node_data.rhs, .handle = node_type.handle }) orelse return;
+                }
+                try node_type.getAllTypesWithHandlesArrayList(arena, types_with_handles);
+                return;
```
Comment (Techatrix) [inline src/features/completions.zig:1349]: This code snippet appears three times in your dot completion code. Perhaps its better move this logic into analysis.
The code duplication seems to have caused a mistake because you are doing `return` instead of `continue` on failure (you are in a for loop here).

I guess you are often looking for a function that does the following conversion:
```rust
match(T) {
    ?P -> P,
    E!P -> P,
    ?E!P -> P,
    else -> T,
}
```
Its like the reverse of type coercion.

**Review by Techatrix — CHANGES_REQUESTED** [review]

**Review by Techatrix — APPROVED** [review]
