### PR TITLE
fix lastToken on tagged union with invalid members

### LINKED ISSUE #1016: New failed assertion relating to scope creation
[Fuzzing group for this issue ↗](https://fuzzing.zigtools.org/group/270dee5233a7d6865c9b9db2277dce9c) (270dee5233a7d6865c9b9db2277dce9c)

## Error

```log
thread 2528 panic: reached unreachable code
/opt/hostedtoolcache/zig/zig-linux-x86_64-0.11.0-dev.1650+5e7b09ce9/x64/lib/std/debug.zig:281:14: 0x344c4c in assert (zls)
    if (!ok) unreachable; // assertion failure
             ^
/home/runner/work/zls/zls/zls/src/ast.zig:534:49: 0x46d5d2 in lastToken (zls)
            std.debug.assert(params.end > params.start);
                                                ^
/home/runner/work/zls/zls/zls/src/offsets.zig:194:104: 0x47b9db in nodeToLoc (zls)
    return .{ .start = tokenToIndex(tree, tree.firstToken(node)), .end = tokenToLoc(tree, ast.lastToken(tree, node)).end };
                                                                                                       ^
/home/runner/work/zls/zls/zls/src/analysis.zig:2541:33: 0x4bac22 in makeInnerScope (zls)
        .loc = offsets.nodeToLoc(tree, node_idx),
                                ^
/home/runner/work/zls/zls/zls/src/analysis.zig:2618:31: 0x420aad in makeScopeInternal (zls)
            try makeInnerScope(allocator, context, node_idx);
                              ^
/home/runner/work/zls/zls/zls/src/analysis.zig:3026:64: 0x424600 in makeScopeInternal (zls)
            try makeScopeInternal(allocator, context, field.ast.value_expr);
                                                               ^
/home/runner/work/zls/zls/zls/src/analysis.zig:2554:30: 0x4bb04c in makeInnerScope (zls)
        try makeScopeInternal(allocator, context, decl);
                             ^
/home/runner/work/zls/zls/zls/src/analysis.zig:2618:31: 0x420aad in makeScopeInternal (zls)
            try makeInnerScope(allocator, context, node_idx);
                              ^
/home/runner/work/zls/zls/zls/src/analysis.zig:2521:33: 0x41f434 in makeDocumentScope (zls)
        .enums = &document_scope.enum_completions,
                                ^
/home/runner/work/zls/zls/zls/src/DocumentStore.zig:210:83: 0x4256db in refreshDocument (zls)
    var new_document_scope = try analysis.makeDocumentScope(self.allocator, handle.tree);
                                                                                  ^
/home/runner/work/zls/zls/zls/src/Server.zig:2146:53: 0x3ef360 in changeDocumentHandler (zls)
    try server.document_store.refreshDocument(handle.uri, new_text);
                                                    ^
/home/runner/work/zls/zls/zls/src/Server.zig:3045:37: 0x3a982f in processMessage (zls)
            const response = handler(server, params) catch |err| {
                                    ^
/home/runner/work/zls/zls/zls/src/Server.zig:2918:26: 0x356ae3 in processJsonRpc (zls)
    server.processMessage(message) catch |err| switch (message) {
                         ^
/home/runner/work/zls/zls/zls/src/main.zig:89:30: 0x355a79 in loop (zls)
        server.processJsonRpc(&arena, json_message);
                             ^
/home/runner/work/zls/zls/zls/src/main.zig:402:13: 0x35767b in main (zls)
    try loop(&server, record_file, replay_file);
            ^
/opt/hostedtoolcache/zig/zig-linux-x86_64-0.11.0-dev.1650+5e7b09ce9/x64/lib/std/start.zig:616:37: 0x33f6a9 in posixCallMainAndExit (zls)
            const result = root.main() catch |err| {
                                    ^
/opt/hostedtoolcache/zig/zig-linux-x86_64-0.11.0-dev.1650+5e7b09ce9/x64/lib/std/start.zig:376:5: 0x33f111 in _start (zls)
    @call(.never_inline, posixCallMainAndExit, .{});
    ^
```

## Latest (at time of filling) entry

|  | Zig | ZLS
| --- | --- | --- |
| Versions | 0.11.0-dev.1650+5e7b09ce9 | 0.11.0-dev.274+8bd5358 |
| Files | [Error ↗](https://fuzzing.zigtools.org/entry/1676854716023/stderr.log) | [Input ↗](https://fuzzing.zigtools.org/entry/1676854716023/stdin.log) |
|  | [Output ↗](https://fuzzing.zigtools.org/entry/1676854716023/stdout.log) | [Zig Repro ↗](https://fuzzing.zigtools.org/entry/1676854716023/principal.zig) |

### PR DESCRIPTION
**Pull request by Techatrix**
fixes #1016

### CODE REVIEW

File: src/ast.zig [hunk 1]
```diff
@@ -572,7 +572,9 @@ pub fn lastToken(tree: Ast, node: Ast.Node.Index) Ast.TokenIndex {
         => {
             end_offset += 2; // for the comma/semicolon + rparen/rbrace
             const params = tree.extraData(datas[n].rhs, Node.SubRange);
-            std.debug.assert(params.end > params.start);
+            if (params.end - params.start == 0) {
```
Comment (leecannon) [inline src/ast.zig:575]: Why not `params.end == params.start`?

Comment (Techatrix) [reply src/ast.zig:575]: I just copied what was used in the switch case for `.call` and `.tagged_union_enum_tag` above it. Its the same in the zig codebase. My only guess is because it adds a safety check for integer overflow.

**Review by leecannon — APPROVED** [review]
