### PR TITLE
explore duplicate packages in build runner

### LINKED ISSUE #1388: mach-core module not being resolved for examples
### Zig Version

0.12.0-dev.15+1c7798a3c

### Zig Language Server Version

d1d4e60d543812231e3afe977f32fc6846c83962

### Steps to Reproduce

clone [mach-core](https://github.com/hexops/mach-core), open the repo in some editor, go to an example app like `examples/two-cubes/main.zig`

### Expected Behavior

the `core` module is resolved and gives completions

### Actual Behavior

the `core` module will not be resolved by `zls`, and there will be no completions

### PR DESCRIPTION
**Pull request by Techatrix**
This will make it easier to get stuck in cycles in the build runner. But in my defense, I think before It was still easily doable to create a build.zig that will loop.
fixes #1388

### CODE REVIEW

**Review by leecannon — DISMISSED** [review]

**Comment by leecannon** [comment]
```
$ git clone https://github.com/CascadeOS/CascadeOS.git
$ cd CascadeOS
$ zig build --build-runner ~/src/zls/src/special/build_runner.zig
error: the following build command crashed:
/home/lee/CascadeOS/zig-cache/o/e594b09ae9903b320f1d9ddf814ad396/build /home/lee/zig/0.12.0-dev.21+ac95cfe44/files/zig /home/lee/CascadeOS /home/lee/CascadeOS/zig-cache /home/lee/.cache/zig
```
with master:
```
$ zig build --build-runner ~/src/zls/src/special/build_runner.zig
{"packages":[{"name":"root","path":"/home/lee/CascadeOS/kernel/root.zig"},{"name":"root","path":"/home/lee/CascadeOS/libraries/ansi/ansi.zig"},{"name":"root","path":"/home/lee/CascadeOS/libraries/bitjuggle/bitjuggle.zig"},{"name":"root","path":"/home/lee/CascadeOS/libraries/core/core.zig"},{"name":"root","path":"/home/lee/CascadeOS/libraries/uuid/uuid.zig"},{"name":"root","path":"/home/lee/CascadeOS/libraries/fs/fs.zig"},{"name":"kernel","path":"/home/lee/CascadeOS/kernel/kernel.zig"},{"name":"cascade_flag","path":"/home/lee/CascadeOS/zig-cache/c/6191ba95a412c13f050c46ca5afc701d/options.zig"},{"name":"cascade_flag","path":"/home/lee/CascadeOS/zig-cache/c/034ae5a8d9f31697fe908e9e91ad3ead/options.zig"}],"include_dirs":["/home/lee/CascadeOS/zig-cache/limine"]}%
```

File: src/special/build_runner.zig [hunk 1]
```diff
@@ -243,9 +243,7 @@ fn processModules(
     for (modules.keys(), modules.values()) |name, mod| {
         const path = mod.builder.pathFromRoot(mod.source_file.getPath(mod.builder));
 
-        const already_added = try packages.addPackage(name, path);
-        // if the package has already been added short circuit here or recursive modules will ruin us
-        if (already_added) return;
+        _ = try packages.addPackage(name, path);
```
Comment (leecannon) [inline src/special/build_runner.zig:246]:
```suggestion
        if (try packages.addPackage(name, path)) continue;
```

**Review by leecannon — CHANGES_REQUESTED** [review]

File: src/special/build_runner.zig (hunk 1 above)
Comment (Techatrix) [reply src/special/build_runner.zig:246]: How did I not realize that I'm in a for loop. My bad.

**Review by leecannon — APPROVED** [review]

**Comment by nullptrdevs** [comment]
Speed is nice, but having completions for all modules obviously is quite needed,
and now that ZLS is threaded :rocket:  maybe it should cover more dependencies?

Also,
```
~/lab/zig/build master *1                                                                                                                                                                    
❯ zig build --build-runner ~/.cache/zls/build_runner.zig
getPath() was called on a GeneratedFile that wasn't built yet.
  source package path: /home/rad/lab/zig
  Is there a missing Step dependency on step 'WriteFile tmp.zig'?
    The step was created by this stack trace:
/home/rad/lab/zig/build/stage3/lib/zig/std/Build/Step/WriteFile.zig:52:26: 0x40b921 in create (build)
        .step = Step.init(.{
                         ^
/home/rad/lab/zig/build/stage3/lib/zig/std/Build.zig:790:33: 0x3813f0 in addWriteFiles (build)
    return Step.WriteFile.create(b);
                                ^
/home/rad/lab/zig/test/src/Cases.zig:520:43: 0x37f3bf in lowerToBuildSteps (build)
        const writefiles = b.addWriteFiles();
                                          ^
/home/rad/lab/zig/test/tests.zig:1173:28: 0x37ed5b in addCases (build)
    cases.lowerToBuildSteps(
                           ^
    Hope that helps. Proceeding to panic.
thread 20099 panic: misconfigured build script
/home/rad/lab/zig/build/stage3/lib/zig/std/Build.zig:1733:17: 0x40c97e in getPath2 (build)
                @panic("misconfigured build script");
                ^
/home/rad/lab/zig/build/stage3/lib/zig/std/Build.zig:1717:24: 0x3a0864 in getPath (build)
        return getPath2(self, src_builder, null);
                       ^
/home/rad/.cache/zls/build_runner.zig:226:60: 0x3694fb in processStep (build)
            _ = try packages.addPackage("root", src.getPath(builder));
                                                           ^
/home/rad/.cache/zls/build_runner.zig:233:28: 0x36968f in processStep (build)
            try processStep(builder, packages, include_dirs, unknown_step);
                           ^
/home/rad/.cache/zls/build_runner.zig:136:28: 0x366cb2 in main (build)
            try processStep(builder, &packages, &include_dirs, step);
                           ^
/home/rad/lab/zig/build/stage3/lib/zig/std/start.zig:574:37: 0x35c00e in posixCallMainAndExit (build)
            const result = root.main() catch |err| {
                                    ^
/home/rad/lab/zig/build/stage3/lib/zig/std/start.zig:243:5: 0x35baf1 in _start (build)
    asm volatile (switch (native_arch) {
    ^
???:?:?: 0x4 in ??? (???)
Unwind information for `???:0x4` was not available, trace may be incomplete

error: the following build command crashed:
/home/rad/lab/zig/zig-cache/o/94d009cab42eb44236f6f76b6a22f9e4/build /home/rad/lab/zig/build/stage4/bin/zig /home/rad/lab/zig /home/rad/lab/zig/zig-cache /home/rad/.cache/zig
```

**Comment by leecannon** [comment]
@nullptrdevs fixed by https://github.com/zigtools/zls/pull/1394
