### PR TITLE
reference fields in anonymous struct initializers

### LINKED ISSUE #1837: Rename doesn't rename struct initialization
### Zig Version

0.12.0-dev.3245+4f782d1e8

### Zig Language Server Version

0.12.0-dev.496+96eddd0

### Client / Code Editor / Extensions

vscode

### Steps to Reproduce and Observed Behavior

Rename field inside TestStruct, initialize struct using syntax below ⇾ the initialization does not get updated

```zig
const TestStruct = struct {
    test_var_renamed: i32, //variable was renamed here
};

test "test" {
    const test_struct: TestStruct = .{
        .test_var = 1, //does not get renamed
    };

    const test_struct2: TestStruct = TestStruct{
        .test_var = 1, //does not get renamed
    };

    std.debug.print("{}", .{test_struct});
    std.debug.print("{}", .{test_struct2});
}

```

### Expected Behavior

```zig
const TestStruct = struct {
    test_var_renamed: i32, //variable was renamed here
};

test "test" {
    const test_struct: TestStruct = .{
        .test_var_renamed = 1, //gets renamed
    };

    const test_struct2: TestStruct = TestStruct{
        .test_var_renamed = 1, //gets renamed
    };

    std.debug.print("{}", .{test_struct});
    std.debug.print("{}", .{test_struct2});
}

```

#398 might be related to this bug

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by xdBronch**
closes #1837 
i was worried about potential performance problems but it seems to be working fine and the same was being done for the `.enum_literal` case anyway
also fixes a bug where quoted field names weren't renamed since it was getting the entire token loc

### CODE REVIEW

File: src/features/references.zig [hunk 1]
```diff
@@ -166,16 +166,36 @@ const Builder = struct {
...
+                        .struct_init_dot_comma,
+                        .struct_init_dot_two,
+                        .struct_init_dot_two_comma,
+                        => try ast.nodesOverlappingIndex(
+                            builder.allocator,
+                            tree,
+                            tree.tokenStart(name_token),
+                        ),
+                        // if this isn't an anonymous struct the type can be determined from the `T{}` directly
+                        else => &.{node},
```
Comment (Techatrix) [inline src/features/references.zig:183]:
```suggestion
                        .struct_init_one,
                        .struct_init_one_comma,
                        .struct_init,
                        .struct_init_comma,
                        => &.{node},
                        else => unreachable,
```

**Review by Techatrix — CHANGES_REQUESTED** [review]

**Review by Techatrix — APPROVED** [review]
