### PR TITLE
Generate folding ranges for empty container types

### LINKED ISSUE #1440: No Fold Point for Empty Struct
### Zig Version

0.11.0 (zls built with 0.12.0-dev.186+e2ff486de)

### Zig Language Server Version

7aeb758

### Steps to Reproduce

Create a file with the following content

```zig
    pub const UserLite = struct {
        id: []const u8,
        name: []const u8,
        username: []const u8,
        host: ?[]const u8,
        avatarUrl: []const u8,
    };

    pub const Foo = struct {
        // hi
    };
```

### Expected Behavior

`Foo` should be foldable in editor (VS Code)

### Actual Behavior

screenshot

### PR DESCRIPTION
**Pull request by nullptrdevs**
Resolves #1440

### CODE REVIEW

File: tests/lsp_features/folding_range.zig [hunk 1]
```diff
@@ -12,6 +12,15 @@ test "foldingRange - empty" {
     try testFoldingRange("", &.{});
 }
 
+test "foldingRange - container type without members" {
+    try testFoldingRange(
+        \\const S = struct {
+        \\};
+    , &.{
+        .{ .startLine = 0, .startCharacter = 16, .endLine = 1, .endCharacter = 0 },
```
Comment (Techatrix) [inline tests/lsp_features/folding_range.zig:20]: the folding range should start after '{'
```suggestion
        .{ .startLine = 0, .startCharacter = 18, .endLine = 1, .endCharacter = 0 },
```

**Review by Techatrix — CHANGES_REQUESTED** [review]

**Review by SuperAuguste — APPROVED** [review]
:)

**Review by Techatrix — APPROVED** [review]
