### PR TITLE
Fix `orelse` type resolution

### LINKED ISSUE #1330: Wrong variable type info when orelse assigns variable with an optional type
### Zig Version

0.11.0-dev.4002+7dd1cf26f

### Zig Language Server Version

8da21e159e3dec9bc6fe01320313cf8108ce4d0b

### Steps to Reproduce

Paste this code into an editor with zls running as lsp.
Send a textDocument/hover request of variable c.
```zig
pub fn opt_test(a: ?i32, b: ?i32) void {
    const c = a orelse b;
    std.debug.print("{s}\n", .{@typeName(@TypeOf(c))});
}
```
Running this code snippet prints ?i32 as type of c.
```zig
const std = @import("std");

pub fn main() !void {
    const a = null;
    const b = null;
    opt_test(a, b);
}

pub fn opt_test(a: ?i32, b: ?i32) void {
    const c = a orelse b;
    std.debug.print("{s}\n", .{@typeName(@TypeOf(c))});
}
```

### Expected Behavior

Type of c being ?i32 .

### Actual Behavior

zls reports the type of c being i32.

I took a stab at trying to come up with a fix by replacing [this switch case](https://github.com/zigtools/zls/blob/8da21e159e3dec9bc6fe01320313cf8108ce4d0b/src/analysis.zig#L1188) with the one below:
```zig
                .@"orelse" => orelse_type: {
                    const base_right = .{ .node = datas[node].rhs, .handle = handle };
                    const base_type_right = (try analyser.resolveTypeOfNodeInternal(base_right));
                    if (base_type_right) |type_right| {
                        const ok = switch (type_right.type.data) {
                            .other => |node_type| switch (node_tags[node_type]) {
                                .optional_type => true,
                                else => false,
                            },
                            else => false,
                        };
                        if (ok) {
                            break :orelse_type base_type;
                        }
                    }
                    break :orelse_type try analyser.resolveUnwrapOptionalType(base_type);
                },
```
This worked for the example above, but when trying to open [hover.zig](src/features/hover.zig) with this change zls crashes.

### PR DESCRIPTION
**Pull request by Sekky61**
Fixes #1330 

See the added tests, they make it pretty clear. One example:

```zig
const foo: ?i32 = 5;
const b<cursor>ar = foo orelse foo;
```

outputs

```zig
?i32
```

This is my first PR so I'd be happy for any pointers.

### CODE REVIEW

**Comment by Sekky61** [comment]
I have just noticed #1728, so I will work on that before opening the PR.

**Comment by Sekky61** [comment]
In the end I opted for a simpler solution. I noticed `orelse` has basically the same problem as `if` and others -- the unification of the types from both child nodes / branches.

I looked into `resolvePeerTypes` and how the `Either` type is used but that may be a discussion for another issue.

File: src/analysis.zig [hunk 1]
```diff
@@ -1853,13 +1859,29 @@ fn resolveTypeOfNodeUncached(analyser: *Analyser, node_handle: NodeWithHandle) e
                 label_token: ?Ast.TokenIndex,
                 then_expr: Ast.Node.Index,
                 else_expr: Ast.Node.Index,
-            } = if (ast.fullWhile(tree, node)) |while_node|
-                .{
+            } = if (ast.fullWhile(tree, node)) |while_node| no_hang: {
+
+                // while (true) {} is a noreturn type
```
Comment (Techatrix) [inline src/analysis.zig:1864]: For this to be correct, you will need to check that the loop has no `break`s. Something like `while (true) { break 5; };` resolves to `comptime_int` instead of `noreturn`. 
We do have the code for resolving the type of `for` or `while` loops based on all the break operand but it is very incomplete. You could work on improving it but that is not really related to the `orelse` operation. Just like you mentioned, an implementation of peer type resolution would be needed.

**Review by Techatrix — CHANGES_REQUESTED** [review]

File: src/analysis.zig (hunk 1 above)
Comment (Sekky61) [reply src/analysis.zig]: Yeah, this was a bit premature. Let's wait for the proper implementation.

**Review by Techatrix — APPROVED** [review]
